/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.IOFile;
import controller.SoLuongException;
import controller.TrongException;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanDoc;
import model.QLMuon;
import model.Sach;

/**
 *
 * @author HUY PHAM
 */
public class FormQLMuon extends javax.swing.JPanel {

    /**
     * Creates new form FormSach
     */
    DefaultTableModel tm;
    private boolean them,sua;
    private String fqlmuon;
    private List<QLMuon> lqlmuon;
    public FormQLMuon() {
        initComponents();
        setSize(900,850);
        String[] cols={"Ma ban doc", "Ho ten", "Ma sach", "Ten sach", "So luong","Tinh trang"}; // cac cot cua bang
        tm = new DefaultTableModel(cols,0); // model cua bang
        jTable1.setModel(tm);
        them=false;
        sua=false;
        fqlmuon ="src/controller/qlmuon.txt";
        loadData();
        loadMaSachVaMaBD();
    }
    private void loadData(){
        File f = new File(fqlmuon);
        if(f.exists()){
            lqlmuon = IOFile.doc(fqlmuon);
        }
        else lqlmuon = new ArrayList<>();
    }
    private void loadMaSachVaMaBD(){
        cbMaBD.removeAllItems();
        cbMaSach.removeAllItems();
        String fsach ="src/controller/sach.txt";
        String fbandoc ="src/controller/bandoc.txt";
        List<BanDoc> listbd = IOFile.doc(fbandoc);
        List<Sach> listsach = IOFile.doc(fsach);
        for(BanDoc i:listbd){
            cbMaBD.addItem(i.getMa()+"");
        }
        for(Sach i:listsach){
            cbMaSach.addItem(i.getMa()+"");
        }
    }
    private boolean trung2Ma(int mabd, int maSach){
        for(QLMuon i:lqlmuon){
            if(i.getBanDoc().getMa()==mabd && i.getSach().getMa()==maSach) return true;
        }
        return false;
    }
    private int demDauSach(int mabd){
        int cnt =0;
        for(QLMuon i:lqlmuon){
            if(i.getBanDoc().getMa()==mabd) cnt++;
        }
        return cnt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        cbSapXep = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        cbMaBD = new javax.swing.JComboBox<>();
        cbMaSach = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThemMoi.setText("Them moi");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnHienThi.setText("Hien thi");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnLuu.setText("Luu vao file");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Lua chon sap xep--", "Ho ten", "So luong sach muon" }));
        cbSapXep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSapXepItemStateChanged(evt);
            }
        });
        cbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemMoi)
                .addGap(67, 67, 67)
                .addComponent(btnHienThi)
                .addGap(71, 71, 71)
                .addComponent(btnLuu)
                .addGap(50, 50, 50)
                .addComponent(cbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi)
                    .addComponent(btnHienThi)
                    .addComponent(btnLuu)
                    .addComponent(cbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel1.setText("Ma bandoc");

        jLabel2.setText("Ma sach");

        jLabel3.setText("So luong muon");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tinh trang sach");

        cbMaBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMaSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tim kiem");

        jButton2.setText("Tim");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(cbMaBD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMaSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbMaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        int mabd = Integer.parseInt(cbMaBD.getSelectedItem().toString());
        int maSach = Integer.parseInt(cbMaSach.getSelectedItem().toString());
        if(trung2Ma(mabd, maSach)){
            JOptionPane.showMessageDialog(this, "Khong duoc trung 2 ma");
            cbMaBD.requestFocus();
            return;
        }
        int sl=0;
        int sltv = getSachByMa(maSach).getSoLuong();
        try{
            sl = Integer.parseInt(jTextField3.getText());
            if(sl>sltv){
                JOptionPane.showMessageDialog(btnThemMoi, "Khong du sach");
                jTextField3.requestFocus();
                return;
            }
            String tt = jTextField4.getText();
            QLMuon ql = new QLMuon(getBDByMa(mabd),getSachByMa(maSach),sl,tt);
            tm.addRow(ql.toObject());
            lqlmuon.add(ql);
            // sua lai so luong sach o thu vien
            String fsach ="src/controller/sach.txt";
            List<Sach> listsach = IOFile.doc(fsach);
            for(Sach i:listsach){
                if(i.getMa()==maSach){
                    i.setSoLuong(sltv-sl);
                }
            }
//            getSachByMa(maSach).setSoLuong(sltv-sl);
            IOFile.viet(fsach, listsach);
       }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Chi nhap so please");
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//        int row = jTable1.getSelectedRow();
//        if(row<0||row>jTable1.getRowCount()){
//            JOptionPane.showMessageDialog(this, "Chon ban doc de sua");
//        }
//        else{
//            jTextField1.setText(jTable1.getValueAt(row, 0).toString());
//            jTextField2.setText(jTable1.getValueAt(row, 1).toString());
//            jTextField3.setText(jTable1.getValueAt(row, 2).toString());
//            jTextField4.setText(jTable1.getValueAt(row, 3).toString());
//        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fqlmuon,lqlmuon);
        tm.setRowCount(0);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        loadData();
        tm.setRowCount(0);
        if(lqlmuon!=null){
            for(QLMuon i:lqlmuon){
                tm.addRow(i.toObject());
            }
        }
        
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadMaSachVaMaBD();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSapXepActionPerformed

    private void cbSapXepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSapXepItemStateChanged
        // TODO add your handling code here:
        if(cbSapXep.getSelectedIndex()==1){
            lqlmuon.sort(new Comparator<QLMuon>(){
                @Override
                public int compare(QLMuon o1, QLMuon o2) {
                    return o1.getBanDoc().getHoten().compareToIgnoreCase(o2.getBanDoc().getHoten());
                }
                
            });
        }
        if(cbSapXep.getSelectedIndex()==2){
            lqlmuon.sort(new Comparator<QLMuon>(){
                @Override
                public int compare(QLMuon o1, QLMuon o2) {
                    return Integer.compare(o1.getSoLuong(), o2.getSoLuong());
                }
                
            });
            Collections.reverse(lqlmuon); // dao nguoc list => giam dan
        }
        tm.setRowCount(0);
        for(QLMuon i:lqlmuon){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_cbSapXepItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tm.setRowCount(0);
        List<QLMuon> lsearch = new ArrayList<>();
        String key = jTextField1.getText();
        for(QLMuon i:lqlmuon){
            if(i.getBanDoc().getHoten().toLowerCase().contains(key)||i.getSach().getTen().toLowerCase().contains(key)){
                lsearch.add(i);
            }
        }
        for(QLMuon i:lsearch){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JComboBox<String> cbMaBD;
    private javax.swing.JComboBox<String> cbMaSach;
    private javax.swing.JComboBox<String> cbSapXep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private Sach getSachByMa(int maSach) {
        String fsach ="src/controller/sach.txt";
        List<Sach> l1=IOFile.doc(fsach);
        if(l1!=null){
            for(Sach i:l1){
                if(i.getMa()==maSach) return i;
            }
        }
        return null;
    }
    private BanDoc getBDByMa(int mabd) {
        String fbandoc ="src/controller/bandoc.txt";
        List<BanDoc> l2=IOFile.doc(fbandoc);
        if(l2!=null){
            for(BanDoc i:l2){
                if(i.getMa()==mabd) return i;
            }
        }
        return null;
    }
}
